:hammer: fix configurations on creation

diff --git a/scripts/up b/scripts/up
--- a/scripts/up
+++ b/scripts/up
@@ -2,34 +2,41 @@
 
 NETWORK='muteus_default'
 
+if ! [ -e .env ]; then
+  echo 'Error: could not find .env, create and update .env first'
+  exit 1
+fi
 . .env
 
 # create network
 docker network inspect $NETWORK > /dev/null
 if [ $? -eq 1 ]; then
   docker network create $NETWORK
+  echo 'Network created'
 fi
 
 # create containers
-docker container inspect muteus_redis
+docker container inspect muteus_redis > /dev/null
 if [ $? -eq 1 ]; then
   docker container create --restart always --name muteus_redis \
-    -v redis_data:/data \
+    -v muteus_redis_data:/data \
     --network $NETWORK \
     redis:alpine
+  echo 'muteus_redis container created'
 fi
 
-docker container inspect muteus_pg
+docker container inspect muteus_pg > /dev/null
 if [ $? -eq 1 ]; then
   docker container create --restart always --name muteus_pg \
-    -v pgdata:/var/lib/postgresql/data \
+    -v muteus_pgdata:/var/lib/postgresql/data \
     --network $NETWORK \
-    -e POSTGRES_USER=$POSTGRES_USER \
-    -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
+    -e POSTGRES_USER=${POSTGRES_USER:?err} \
+    -e POSTGRES_PASSWORD=${POSTGRES_PASS:?err} \
     postgres:12-alpine
+  echo 'muteus_pg container created'
 fi
 
-docker container inspect muteus_galactus
+docker container inspect muteus_galactus > /dev/null
 if [ $? -eq 1 ]; then
   docker container create --restart always --name muteus_galactus \
     --network $NETWORK \
@@ -39,26 +46,28 @@ if [ $? -eq 1 ]; then
     -e REDIS_ADDR=${GALACTUS_REDIS_ADDR} \
     -e GALACTUS_PORT=${GALACTUS_PORT} \
     automuteus/galactus:${GALACTUS_TAG:?err}
+  echo 'muteus_galactus container created'
 fi
 
 docker container inspect muteus_automuteus
 if [ $? -eq 1 ]; then
   docker container create --restart always --name muteus_automuteus \
-    -v botlogs:/app/logs \
+    -v muteus_botlogs:/app/logs \
     --network $NETWORK \
     -p ${SERVICE_PORT:-5000}:5000 \
     -e DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:?err} \
     -e HOST=${GALACTUS_HOST:?err} \
     -e POSTGRES_USER=${POSTGRES_USER:?err} \
-    -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err} \
+    -e POSTGRES_PASS=${POSTGRES_PASS:?err} \
     -e WORKER_BOT_TOKENS=${WORKER_BOT_TOKENS:-} \
     -e EMOJI_GUILD_ID=${EMOJI_GUILD_ID:-} \
     -e CAPTURE_TIMEOUT=${CAPTURE_TIMEOUT:-} \
     -e AUTOMUTEUS_LISTENING=${AUTOMUTEUS_LISTENING:-} \
-    -e REDIS_ADDR=${REDIS_ADDR} \
+    -e REDIS_ADDR=${AUTOMUTEUS_REDIS_ADDR} \
     -e GALACTUS_ADDR=${GALACTUS_ADDR} \
     -e POSTGRES_ADDR=${POSTGRES_ADDR} \
     denverquane/amongusdiscord:${AUTOMUTEUS_TAG:?err}
+  echo 'muteus_automuteus container created'
 fi
 
 # start containers
